
export type CianParseItem = {
    "offerType": string,
    "isCommercialOwnershipVerified": boolean,
    "videos": [],
    "cianUserId": number,
    "isCalltrackingEnabled": boolean,
    "externalId": null,
    "isInHiddenBase": boolean,
    "fullUrl": string,
    "balconiesCount": null,
    "readyBusinessType": null,
    "newbuilding": null,
    "geo": {
        "jk": null,
        "buildingAddress": null,
        "railways":{
                "name": string,
                "geoType": "railway",
                "directionIds": number[],
                "id": number,
                "travelType": string,
                "distance": number,
                "time": number,
                "qs": string
        }[], 
        "address": {
            "type": "location",
            "shortName": string,
            "name": string,
            "qs": string,
            "geoType": "location",
            "title": string,
            "id": number,
            "isFormingAddress": boolean,
            "fullName": string,
            "locationTypeId": number
        }[],
        "userInput": string,
        "districts": string[],
        "countryId": number,
        "highways": {
            "name": string,
            "isDefault": boolean,
            "qs": string,
            "geoType": "highway",
            "id": number,
            "distance": string
        }[],
        "coordinates": {
            "lng": number,
            "lat": number
        },
        "undergrounds": [],
        "sortedGeoIds": {
            "type": "railway" | "highway",
            "id": number
        }[], 
    },
    "land": {
        "type": null,
        "status": null,
        "areaUnitType": "sotka",
        "possibleToChangeStatus": null,
        "area": string
    },
    "permittedUseType": null,
    "allFromOffrep": null,
    "status": "published",
    "rentByPartsDescription": null,
    "shareAmount": null,
    "category": string,
    "garage": null,
    "buildingCadastralNumber": null,
    "isApartments": null,
    "phones": [{
        "countryCode": string,
        "number": string
    }],
    "photos": {
        "rotateDegree": null,
        "isLayout": boolean,
        "isDefault": boolean,
        "id": number,
        "thumbnailUrl": string,
        "fullUrl": string,
        "miniUrl": string,
        "thumbnail2Url": string
    }[],
    "id": number,
    "showWarningMessage": boolean,
    "title": "Современный трёхэтажный таунхаус",
    "roomsCount": null,
    "kp": {
        "id": number,
        "builderId": number,
        "counterSet": {
            "onSale": number,
            "sold": number,
            "total": number,
            "underConstruction": number
        },
        "displayBuilderPhone": boolean,
        "imageUrl": string,
        "locationId": number,
        "name": string,
        "url": string,
        "villageClass": "business",
        "villageAdvantages": {
            "advantageType": "gas" | "water" | "education",
            "advantageTypeDetails": ["main_gas" | "lake" | "kindergarten"],
            "text": string
        }[], 
    },
    "isByCommercialOwner": null,
    "isExcludedFromAction": boolean,
    "booking": null,
    "publishedUserId": number,
    "businessShoppingCenter": null,
    "layout": null,
    "isPremium": boolean,
    "rosreestrCheck": null,
    "accessType": null,
    "added": string,
    "jkUrl": null,
    "roomArea": null,
    "decoration": null,
    "isNew": boolean,
    "specialty": {
        "specialties": [],
        "types": [],
        "additionalTypes": []
    },
    "bargainTerms": {
        "clientFee": null,
        "leaseTermType": null,
        "agentFee": null,
        "mortgageAllowed": null,
        "utilitiesTerms": null,
        "paymentPeriod": null,
        "currency": "rur",
        "agentBonus": null,
        "tags": [],
        "leaseType": null,
        "priceRur": number,
        "vatType": null,
        "priceForWorkplace": null,
        "bargainAllowed": null,
        "price": number,
        "deposit": null,
        "saleType": null,
        "vatPrice": null,
        "priceType": "all"
    },
    "building": {
        "buildYear": null,
        "deadline": null,
        "type": null,
        "parking": null,
        "floorsCount": number,
        "heatingType": null,
        "accessType": null,
        "passengerLiftsCount": null,
        "materialType": null,
        "classType": null,
        "cargoLiftsCount": null
    },
    "cianId": number,
    "description": string,
    "demolishedInMoscowProgramm": null,
    "moderationInfo": {
        "showContactWarningMessage": boolean,
        "photoStub": null,
        "warningMessage": null
    },
    "humanizedTimedelta": string,
    "livingArea": null,
    "dealType": string,
    "addedTimestamp": number,
    "isImported": boolean,
    "offerInDeal": boolean,
    "isColorized": boolean,
    "creationDate": string,
    "descriptionWordsHighlighted": [],
    "coworking": null,
    "workTimeInfo": null,
    "isRecidivist": boolean,
    "basicProfiScore": string,
    "categoriesIds": number[],
    "bedroomsCount": number,
    "cadastralNumber": null,
    "kitchenArea": null,
    "isRentByParts": boolean,
    "isStandard": boolean,
    "workplaceCount": null,
    "descriptionMinhash": number[],
    "similar": null,
    "isCianPartner": boolean,
    "loggiasCount": null,
    "commercialOwnership": null,
    "isByHomeowner": null,
    "flatType": null,
    "coworkingOfferType": null,
    "floorNumber": null,
    "totalArea": string | null,
    "areaParts": null,
    "roomsForSaleCount": null,
    "dealRentVersion": null,
    "monthlyIncome": null,
    "newbuildingVasPromotion": null,
    "isNeedHideExactAddress": boolean,
    "isTop3": boolean,
    "userId": number,
    "officeType": null,
    "isAuction": boolean,
    "villageMortgageAllowed": boolean,
    "promoInfo": null,
    "minArea": null,
    "fromDeveloper": null,
    "isDuplicatedDescription": boolean,
    "isFavorite": boolean,
    "notes": {
        "offer": null,
        "realtor": null
    },
    "user": {
        "cianUserId": string,
        "isAgent": boolean,
        "isBuilder": boolean,
        "isCallbackUser": boolean,
        "isCianPartner": boolean,
        "isHidden": boolean,
        "isPassportVerified": boolean,
        "isSubAgent": boolean,
        "userId": number,
        "userTrustLevel": string,
        "accountType": string,
        "agencyName": string,
        "agentAvatarUrl": string,
        "agentModerationInfo": {
            "isUserIdentified": boolean,
            "isUserIdentifiedByDocuments": boolean,
            "userLevelInfo": {
                "hasVerifiedDocuments": boolean,
                "levelName": string,
                "levelOrder": number,
                "levelSystemName": string
            }
        },
        "billingInfo": {
            "accountType": number,
            "packages": {
                "countryId": number,
                "depositRequired": boolean,
                "geoName": string,
                "locationId": number,
                "packageTypeId": number,
                "packageTypeName": string
            }[],
            "removeCompetitor": boolean,
            "replenishDisabled": boolean
        },
        "canShowOnline": boolean,
        "cianProfileStatus": string,
        "companyName": string,
        "experience": string,
        "isChatsEnabled": boolean,
        "isSelfEmployed": boolean,
        "phoneNumbers": {
            "countryCode": string,
            "number": string
        }[],
        "profileUri": string,
        "userType": string,
        "personalRating": null,
        "agentAvailability": {
            "available": boolean,
            "userId": number
        },
        "agentLists": []
    },
    "isPro": boolean,
    "gaLabel": string,
    "adfoxParams": {
        "puid1": string,
        "puid2": string,
        "puid5": string,
        "puid6": string,
        "puid8": number,
        "puid10": string,
        "puid13": string,
        "puid16": string,
        "puid17": string,
        "puid19": string,
        "puid36": number
    },
    "chatId": null,
    "chat": {
        "chatId": null,
        "canSendMessage": boolean
    },
    "isResale": boolean,
    "auction": null,
    "isUnique": boolean,
    "hasFairPrice": boolean,
    "savedSearchLabels": [],
    "isDealRequestSubstitutionPhone": boolean,
    "isNewbuildingTourAvailable": boolean,
    "comparisonStatus": null,
    "photoFeatureIcons": [],
    "offerFeatureLabels": [],
    "factoids": [],
    "isBookedFromDeveloper": boolean,
    "brandingLevel": "thirdLevel",
    "isRosreestrChecked": boolean,
    "newbuildingDynamicCalltracking": {
        "siteBlockId": null
    },
    "bestPlaceAnalyticsAvailable": null,
    "showGalleryThumbnails": boolean
}
